spring.application.name=RecruitMate

spring.data.mongodb.uri=mongodb+srv://rastogimanas329:Ys54a4sUZbZpCxhP@cluster0.vl8euvm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=recruitmate
server.servlet.context-path=/RecruitMate
